REPO_PATH = 'D:\COLLEGE\YEAR3\SEM2\CNPM\TEST'
OPENAI_API_KEY = 'sk-proj-ZkTT9O1rdS5GHKLxchS4T3BlbkFJi2fbxiFMGFvbIPidT2cc'
CONTEXT_PATH_DEFAULT = 'sample_convention.txt'
COMMIT_COLLECTION = 'commit_collection'